"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class motor_cmd_t(object):

    __slots__ = ["q_des_abad", "q_des_hip", "q_des_knee", "qd_des_abad", "qd_des_hip", "qd_des_knee", "kp_abad", "kp_hip", "kp_knee", "kd_abad", "kd_hip", "kd_knee", "tau_abad_ff", "tau_hip_ff", "tau_knee_ff", "contactFlag"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4]]

    def __init__(self):
        self.q_des_abad = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.q_des_hip = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.q_des_knee = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.qd_des_abad = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.qd_des_hip = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.qd_des_knee = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.kp_abad = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.kp_hip = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.kp_knee = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.kd_abad = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.kd_hip = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.kd_knee = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.tau_abad_ff = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.tau_hip_ff = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.tau_knee_ff = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.contactFlag = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """

    def encode(self):
        buf = BytesIO()
        buf.write(motor_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.q_des_abad[:4]))
        buf.write(struct.pack('>4f', *self.q_des_hip[:4]))
        buf.write(struct.pack('>4f', *self.q_des_knee[:4]))
        buf.write(struct.pack('>4f', *self.qd_des_abad[:4]))
        buf.write(struct.pack('>4f', *self.qd_des_hip[:4]))
        buf.write(struct.pack('>4f', *self.qd_des_knee[:4]))
        buf.write(struct.pack('>4f', *self.kp_abad[:4]))
        buf.write(struct.pack('>4f', *self.kp_hip[:4]))
        buf.write(struct.pack('>4f', *self.kp_knee[:4]))
        buf.write(struct.pack('>4f', *self.kd_abad[:4]))
        buf.write(struct.pack('>4f', *self.kd_hip[:4]))
        buf.write(struct.pack('>4f', *self.kd_knee[:4]))
        buf.write(struct.pack('>4f', *self.tau_abad_ff[:4]))
        buf.write(struct.pack('>4f', *self.tau_hip_ff[:4]))
        buf.write(struct.pack('>4f', *self.tau_knee_ff[:4]))
        buf.write(struct.pack('>4f', *self.contactFlag[:4]))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_cmd_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = motor_cmd_t()
        self.q_des_abad = struct.unpack('>4f', buf.read(16))
        self.q_des_hip = struct.unpack('>4f', buf.read(16))
        self.q_des_knee = struct.unpack('>4f', buf.read(16))
        self.qd_des_abad = struct.unpack('>4f', buf.read(16))
        self.qd_des_hip = struct.unpack('>4f', buf.read(16))
        self.qd_des_knee = struct.unpack('>4f', buf.read(16))
        self.kp_abad = struct.unpack('>4f', buf.read(16))
        self.kp_hip = struct.unpack('>4f', buf.read(16))
        self.kp_knee = struct.unpack('>4f', buf.read(16))
        self.kd_abad = struct.unpack('>4f', buf.read(16))
        self.kd_hip = struct.unpack('>4f', buf.read(16))
        self.kd_knee = struct.unpack('>4f', buf.read(16))
        self.tau_abad_ff = struct.unpack('>4f', buf.read(16))
        self.tau_hip_ff = struct.unpack('>4f', buf.read(16))
        self.tau_knee_ff = struct.unpack('>4f', buf.read(16))
        self.contactFlag = struct.unpack('>4f', buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if motor_cmd_t in parents: return 0
        tmphash = (0x8420b9c42b30be1d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if motor_cmd_t._packed_fingerprint is None:
            motor_cmd_t._packed_fingerprint = struct.pack(">Q", motor_cmd_t._get_hash_recursive([]))
        return motor_cmd_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", motor_cmd_t._get_packed_fingerprint())[0]

